version: '3.7'

services:
  db:
    image: postgres:latest
    restart: 'no'
    ports:
    - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev
  rabbit:
    hostname: rabbit
    image: rabbitmq:management
    env_file:
      - env.rabbit.dev
    ports:
      - "5673:5672"
      - "15672:15672"
  redis:
    image: 'redis:3.0-alpine'
    command: redis-server
    volumes:
      - 'redis:/data'
    ports:
      - '6379:6379'
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn -b 0.0.0.0:5000 --reload  --max-requests 1000 --timeout 30 wsgi:app
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  worker:
    build:
      context: ./
      dockerfile: Dockerfile
    command: celery -A make_celery worker -l info
    env_file:
      - .env.dev
    depends_on:
      - db
      - rabbit
      - redis

volumes:
  postgres_data:
  redis: