version: '3.7'

services:
  db:
    image: postgres:latest
    restart: 'no'
    ports:
    - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn -b 0.0.0.0:5000 --reload  --max-requests 1000 --timeout 30 wsgi:app
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db

volumes:
  postgres_data:
