version: '3.7'

services:
  db:
    image: postgres:latest
    restart: 'no'
    ports:
    - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
  app:
    build:
      context: ./Backend
      dockerfile: ../Dockerfile
    command: flask run --host=0.0.0.0
    volumes:
      - ./Backend:/Api/Backend
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db

volumes:
  postgres_data: