version: '3.7'

services:
  app:
    build: ./Backend
    command: flask run --host=0.0.0.0
    volumes:
      - ./Backend:/Api/Backend
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev

    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    command: "true"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=git_api_db

volumes:
  postgres_data:
